services:
  bun:
    image: oven/bun:1.2.22
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: sh -c "bun run dev"

  postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_DB: fitscore
      POSTGRES_PASSWORD: toor
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: >
      bash -c "
      set -e;
      docker-entrypoint.sh postgres;
      psql -U \"postgres\" -d \"bakulai\" -c \"CREATE EXTENSION IF NOT EXISTS vector;\"
      "

volumes:
  postgres_data: